services:
  mysql:
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - 'MYSQL_DATABASE=cards'
      - 'MYSQL_ROOT_PASSWORD=Root123#@!'

    ports:
      - '3306:3306'
